# NOTE: This file is auto generated by OpenAPI Generator 7.1.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MBTA.Model.ActivePeriod do
  @moduledoc """
  Start and End dates for active alert
  """

  @derive Jason.Encoder
  defstruct [
    :start,
    :end
  ]

  @type t :: %__MODULE__{
    :start => DateTime.t | nil,
    :end => DateTime.t | nil
  }

  alias MBTA.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:start, :datetime, nil)
     |> Deserializer.deserialize(:end, :datetime, nil)
  end
end

