# NOTE: This file is auto generated by OpenAPI Generator 7.1.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MBTA.Model.AlertResourceRelationships do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :facility
  ]

  @type t :: %__MODULE__{
    :facility => MBTA.Model.AlertResourceRelationshipsFacility.t | nil
  }

  alias MBTA.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:facility, :struct, MBTA.Model.AlertResourceRelationshipsFacility)
  end
end

