# NOTE: This file is auto generated by OpenAPI Generator 7.1.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MBTA.Model.BadRequestErrorsInner do
  @moduledoc """
  A JSON-API error when a bad request is received
  """

  @derive Jason.Encoder
  defstruct [
    :status,
    :source,
    :detail,
    :code
  ]

  @type t :: %__MODULE__{
    :status => String.t | nil,
    :source => MBTA.Model.BadRequestErrorsInnerSource.t | nil,
    :detail => String.t | nil,
    :code => String.t | nil
  }

  alias MBTA.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:source, :struct, MBTA.Model.BadRequestErrorsInnerSource)
  end
end

