# NOTE: This file is auto generated by OpenAPI Generator 7.1.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MBTA.Model.FacilityResourceAttributes do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :type,
    :short_name,
    :properties,
    :longitude,
    :long_name,
    :latitude
  ]

  @type t :: %__MODULE__{
    :type => String.t | nil,
    :short_name => String.t | nil,
    :properties => [MBTA.Model.FacilityProperty.t] | nil,
    :longitude => float() | nil,
    :long_name => String.t | nil,
    :latitude => float() | nil
  }

  alias MBTA.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:properties, :list, MBTA.Model.FacilityProperty)
  end
end

