# NOTE: This file is auto generated by OpenAPI Generator 7.1.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MBTA.Model.FacilityResourceRelationships do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :stop
  ]

  @type t :: %__MODULE__{
    :stop => MBTA.Model.PredictionResourceRelationshipsStop.t | nil
  }

  alias MBTA.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:stop, :struct, MBTA.Model.PredictionResourceRelationshipsStop)
  end
end

