# NOTE: This file is auto generated by OpenAPI Generator 7.1.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MBTA.Model.Forbidden do
  @moduledoc """
  A JSON-API error document when the API key is invalid
  """

  @derive Jason.Encoder
  defstruct [
    :errors
  ]

  @type t :: %__MODULE__{
    :errors => [MBTA.Model.ForbiddenErrorsInner.t]
  }

  alias MBTA.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:errors, :list, MBTA.Model.ForbiddenErrorsInner)
  end
end

