# NOTE: This file is auto generated by OpenAPI Generator 7.1.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MBTA.Model.ForbiddenErrorsInner do
  @moduledoc """
  A JSON-API error when an invalid API key is received
  """

  @derive Jason.Encoder
  defstruct [
    :status,
    :code
  ]

  @type t :: %__MODULE__{
    :status => String.t | nil,
    :code => String.t | nil
  }

  def decode(value) do
    value
  end
end

