# NOTE: This file is auto generated by OpenAPI Generator 7.1.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MBTA.Model.LineResourceAttributes do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :text_color,
    :sort_order,
    :short_name,
    :long_name,
    :color
  ]

  @type t :: %__MODULE__{
    :text_color => String.t | nil,
    :sort_order => integer() | nil,
    :short_name => String.t | nil,
    :long_name => String.t | nil,
    :color => String.t | nil
  }

  def decode(value) do
    value
  end
end

