# NOTE: This file is auto generated by OpenAPI Generator 7.1.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MBTA.Model.LiveFacilitiesLinks do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :self,
    :prev,
    :next,
    :last,
    :first
  ]

  @type t :: %__MODULE__{
    :self => String.t | nil,
    :prev => String.t | nil,
    :next => String.t | nil,
    :last => String.t | nil,
    :first => String.t | nil
  }

  def decode(value) do
    value
  end
end

