# NOTE: This file is auto generated by OpenAPI Generator 7.1.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MBTA.Model.NotFoundErrorsInner do
  @moduledoc """
  A JSON-API error when a resource is not found
  """

  @derive Jason.Encoder
  defstruct [
    :title,
    :status,
    :source,
    :code
  ]

  @type t :: %__MODULE__{
    :title => String.t | nil,
    :status => String.t | nil,
    :source => MBTA.Model.NotFoundErrorsInnerSource.t | nil,
    :code => String.t | nil
  }

  alias MBTA.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:source, :struct, MBTA.Model.NotFoundErrorsInnerSource)
  end
end

