# NOTE: This file is auto generated by OpenAPI Generator 7.1.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MBTA.Model.NotFoundErrorsInnerSource do
  @moduledoc """
  A JSON-API error source
  """

  @derive Jason.Encoder
  defstruct [
    :parameter
  ]

  @type t :: %__MODULE__{
    :parameter => String.t | nil
  }

  def decode(value) do
    value
  end
end

