# NOTE: This file is auto generated by OpenAPI Generator 7.1.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MBTA.Model.OccupancyResourceAttributes do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :status,
    :percentage
  ]

  @type t :: %__MODULE__{
    :status => String.t | nil,
    :percentage => integer() | nil
  }

  def decode(value) do
    value
  end
end

