# NOTE: This file is auto generated by OpenAPI Generator 7.1.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MBTA.Model.RoutePatternResourceRelationships do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :route,
    :representative_trip
  ]

  @type t :: %__MODULE__{
    :route => MBTA.Model.PredictionResourceRelationshipsRoute.t | nil,
    :representative_trip => MBTA.Model.RoutePatternResourceRelationshipsRepresentativeTrip.t | nil
  }

  alias MBTA.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:route, :struct, MBTA.Model.PredictionResourceRelationshipsRoute)
     |> Deserializer.deserialize(:representative_trip, :struct, MBTA.Model.RoutePatternResourceRelationshipsRepresentativeTrip)
  end
end

