# NOTE: This file is auto generated by OpenAPI Generator 7.1.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MBTA.Model.ScheduleResourceAttributes do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :timepoint,
    :stop_sequence,
    :stop_headsign,
    :pickup_type,
    :drop_off_type,
    :direction_id,
    :departure_time,
    :arrival_time
  ]

  @type t :: %__MODULE__{
    :timepoint => boolean() | nil,
    :stop_sequence => integer() | nil,
    :stop_headsign => String.t | nil,
    :pickup_type => integer() | nil,
    :drop_off_type => integer() | nil,
    :direction_id => integer() | nil,
    :departure_time => DateTime.t | nil,
    :arrival_time => DateTime.t | nil
  }

  alias MBTA.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:departure_time, :datetime, nil)
     |> Deserializer.deserialize(:arrival_time, :datetime, nil)
  end
end

