# NOTE: This file is auto generated by OpenAPI Generator 7.1.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MBTA.Model.Schedules do
  @moduledoc """
  A page of [ScheduleResource](#scheduleresource) results
  """

  @derive Jason.Encoder
  defstruct [
    :links,
    :data
  ]

  @type t :: %__MODULE__{
    :links => MBTA.Model.LiveFacilitiesLinks.t | nil,
    :data => [MBTA.Model.ScheduleResource.t]
  }

  alias MBTA.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:links, :struct, MBTA.Model.LiveFacilitiesLinks)
     |> Deserializer.deserialize(:data, :list, MBTA.Model.ScheduleResource)
  end
end

