# NOTE: This file is auto generated by OpenAPI Generator 7.1.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MBTA.Model.StopResourceRelationships do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :parent_station
  ]

  @type t :: %__MODULE__{
    :parent_station => MBTA.Model.StopResourceRelationshipsParentStation.t | nil
  }

  alias MBTA.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:parent_station, :struct, MBTA.Model.StopResourceRelationshipsParentStation)
  end
end

