# NOTE: This file is auto generated by OpenAPI Generator 7.1.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MBTA.Model.TripResourceRelationshipsRoutePattern do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :links,
    :data
  ]

  @type t :: %__MODULE__{
    :links => MBTA.Model.TripResourceRelationshipsRoutePatternLinks.t | nil,
    :data => MBTA.Model.TripResourceRelationshipsRoutePatternData.t | nil
  }

  alias MBTA.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:links, :struct, MBTA.Model.TripResourceRelationshipsRoutePatternLinks)
     |> Deserializer.deserialize(:data, :struct, MBTA.Model.TripResourceRelationshipsRoutePatternData)
  end
end

