# NOTE: This file is auto generated by OpenAPI Generator 7.1.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MBTA.Model.TripResourceAttributes do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :wheelchair_accessible,
    :name,
    :headsign,
    :direction_id,
    :block_id,
    :bikes_allowed
  ]

  @type t :: %__MODULE__{
    :wheelchair_accessible => integer() | nil,
    :name => String.t | nil,
    :headsign => String.t | nil,
    :direction_id => integer() | nil,
    :block_id => String.t | nil,
    :bikes_allowed => integer() | nil
  }

  def decode(value) do
    value
  end
end

