# NOTE: This file is auto generated by OpenAPI Generator 7.1.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MBTA.Model.VehicleResourceRelationships do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :trip,
    :stop,
    :route
  ]

  @type t :: %__MODULE__{
    :trip => MBTA.Model.PredictionResourceRelationshipsTrip.t | nil,
    :stop => MBTA.Model.PredictionResourceRelationshipsStop.t | nil,
    :route => MBTA.Model.PredictionResourceRelationshipsRoute.t | nil
  }

  alias MBTA.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:trip, :struct, MBTA.Model.PredictionResourceRelationshipsTrip)
     |> Deserializer.deserialize(:stop, :struct, MBTA.Model.PredictionResourceRelationshipsStop)
     |> Deserializer.deserialize(:route, :struct, MBTA.Model.PredictionResourceRelationshipsRoute)
  end
end

