# NOTE: This file is auto generated by OpenAPI Generator 7.1.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MBTA.Model.VehicleResourceAttributes do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :updated_at,
    :speed,
    :occupancy_status,
    :longitude,
    :latitude,
    :label,
    :direction_id,
    :current_stop_sequence,
    :current_status,
    :carriages,
    :bearing
  ]

  @type t :: %__MODULE__{
    :updated_at => DateTime.t | nil,
    :speed => float() | nil,
    :occupancy_status => String.t | nil,
    :longitude => float() | nil,
    :latitude => float() | nil,
    :label => String.t | nil,
    :direction_id => integer() | nil,
    :current_stop_sequence => integer() | nil,
    :current_status => String.t | nil,
    :carriages => [MBTA.Model.VehicleResourceAttributesCarriagesInner.t] | nil,
    :bearing => integer() | nil
  }

  alias MBTA.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:updated_at, :datetime, nil)
     |> Deserializer.deserialize(:carriages, :list, MBTA.Model.VehicleResourceAttributesCarriagesInner)
  end
end

